### PR TITLE
Don't leave AttributeBuilder in an inconsistent state on exceptions

### PR DESCRIPTION
**Pull request by koterpillar**
When one of the LazyValues raises an exception, don't leave its name in __pending stack of the AttributeBuilder, preventing evaluation of any other LazyValues.

The use case for this is: several declarations on a factory have to be in sync with each other, but can supply default values if needed. For example:

```python
class UserFactory(factory.Factory):
    @factory.lazy_attribute
    def username(self):
        return self.email[:self.email.index('@')]

    @factory.lazy_attribute
    def email(self):
        try:
            return self.username + '@example.com'
        except factory.containers.CyclicDefinitionError:
            return 'dummy@example.com'
````

This allows any of the following:

```python
UserFactory(username='jane')
UserFactory(email='jane@somewhere.com')
UserFactory()
```

### CODE REVIEW

**Comment by rbarrois** [comment]
Hmm, the idea is quite interesting!

However, I'd like to find a cleaner way to handle it than to rely on cyclic definition; I'll try to think of a cleaner API (maybe with some helper).

I'll keep this PR open for now, I hope to get some more time to think about this next week :)

**Comment by koterpillar** [comment]
Regardless of `CyclicDefinitionError`, _any_ exception raised by a declaration will make `AttributeBuilder` unusable. This won't normally present problems as `AttributeBuilder` is recreated each time the factory is built. However, leaving it in an inconsistent state is not something that should happen at all, in my opinion.

**Comment by koterpillar** [comment]
Is there any decision on this?

**Comment by rbarrois** [comment]
Well, the change improves reliability, so let's go ;)

However, for the record, I do not advise relying on ``CyclicDefinitionError`` ;)

**Pull request merged**
