### PR TITLE
Check logger for DEBUG before calling log_pprint

### PR DESCRIPTION
**Pull request by xavfernandez**

### CODE REVIEW

**Comment by adamchainz** [comment]
+1 factory boy logging, mostly in `_safe_repr`, was taking a significant amount of my test suite - around ~5-10%, though hard to tell as things slow down when running with the profiler.

**Comment by adamchainz** [comment]
Had an idea - rather than wrapping with this request, log_pprint could be made to return a lazy object whose __str__ is the result of the formatting with safe_repr. This would require fewer, cleaner changes now, plus would work for future logging statements that get added..

**Comment by adamchainz** [comment]
Also, for anyone else that notices this performance penalty, this is how I'm currently obviating it with [patchy](https://github.com/adamchainz/patchy):

```
def patch_factory_boy_util_log_pprint():
    """
    This function is used to generate log output for factory boy, unfortunately it takes a lot of CPU time on
    many-factory tests
    """
    from factory.utils import log_pprint
    patchy.patch(log_pprint, """\
        @@ -1,9 +1,2 @@
         def log_pprint(args=(), kwargs=None):
        +    return
        -    kwargs = kwargs or {}
        -    return ', '.join(
        -        [_safe_repr(arg) for arg in args] +
        -        [
        -            '%s=%s' % (key, _safe_repr(value))
        -            for key, value in kwargs.items()
        -        ]
        -    )
        """)
```

**Comment by xavfernandez** [comment]
I like the lazy log_pprint idea better indeed :) :+1:

**Comment by rbarrois** [comment]
Thanks for the suggestion! I've just implemented the "lazy pprint" approach.

**Comment by adamchainz** [comment]
+1 thanks, was just looking at implementing it myself

**Pull request closed without merging**
