### PR TITLE
Add custom error message when django_get_or_create is missing an input.

### PR DESCRIPTION
**Pull request by rrauenza**
Ok, I couldn't figure out how to squash it, so just recreated the change after rewinding and resyncing with upstream.

### CODE REVIEW

**Comment by jeffwidman** [comment]
Continuation of #290 

LGTM, though I'm going ot hold off merging until @rbarrois looks at it as he's the Django point person.

**Comment by rrauenza** [comment]
Sure.  The underlying problem is trying to populate the Django get_or_create args, but when an initial value isn't provided, it just throws a KeyError -- so I just throw a more informative error message instead pointing to the root cause.

**Comment by rrauenza** [comment]
@rbarrois , alternatively `key_fields[field] = kwargs.pop(field)` could be changed to              `key_fields[field] = kwargs.pop(field, None)`
 
 That's definitely more of a design decision there... because None could be a valid value in the Model.

**Comment by rbarrois** [comment]
@rrauenza This looks good :)

I'm merging it, but it would be great if you could add a small test checking that this works as expected: the amount of meta-programming inherent to factory_boy is known to cause unexpected behaviour :/

**Comment by rrauenza** [comment]
See https://github.com/rbarrois/factory_boy/issues/297

**Pull request merged**
