### PR TITLE
Peewee support - update

### PR DESCRIPTION
**Pull request by arnuschky**
This adds peewee ORM support.
Based on code from https://github.com/cam-stitt
Basically a port of https://github.com/rbarrois/factory_boy/pull/82

### CODE REVIEW

**Comment by mgaitan** [comment]
will be it be fixed and merged? could I help? it would a very useful addition.

**Comment by fgimian** [comment]
Great work! +1 to this please :smile:

**Comment by arnuschky** [comment]
@cam-stitt went through the trouble to break out the code into a separate plugin.
You can find the plugin here: https://github.com/cam-stitt/factory_boy-peewee

**Comment by fgimian** [comment]
Thank you guys! :smile:

**Pull request closed without merging**
